// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Return Simon Babouhot's professional profile summary (role, location, focus areas).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Simon Babouhot",
      role: "Product Owner",
      focus: "Digital transformation & customer experience",
      locations: ["Nouvelle-Cal\xE9donie", "France"],
      summary: "Product Owner with 5+ years of experience (Allianz), bridging product vision, UX, and business operations. Focus on shipping products people actually use \u2014 for end customers and the teams that support them.",
      offerings: [
        {
          title: "Product Management",
          items: [
            "Strategic framing (vision, goals, stakeholder alignment)",
            "End-to-end delivery (backlog, user stories, UAT, release)",
            "Performance steering (KPIs, dataviz, adoption)"
          ]
        },
        {
          title: "Process optimization & AI automation",
          items: [
            "Key process analysis",
            "Simple automation systems",
            "ROI-oriented approach"
          ]
        }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List experience",
  description: "List Simon Babouhot's professional experience with highlights and outcomes.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const experience = [
      {
        role: "Product Owner, Digital Customer Space",
        company: "Allianz",
        period: "Since 2021",
        highlights: [
          "End-to-end pilot of a 330,000-user customer space, from discovery to production.",
          "Activation +15 pts: from 50% to 65% of portfolio via adoption-focused redesign.",
          "Digitized claims journey: +60% online submissions, -20% declaration time.",
          "Interface between customer, business and IT \u2014 balancing user and employee experience."
        ]
      },
      {
        role: "Business Developer, Affiliation & E-partnerships",
        period: "2020\u20132021",
        highlights: [
          "Managed acquisition campaigns: display, affiliation, emailing, SEA.",
          "Performance steering: analysis, continuous optimization, reporting.",
          "Rebuilt communications: campaign kits & assets."
        ]
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
      structuredContent: { experience }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool3({
  name: "get_contact",
  title: "Get contact",
  description: "Return contact channels to reach Simon Babouhot (booking link, site sections).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      booking: "https://calendly.com/simonbabouhot-pro/30min",
      contactSection: "https://simonbabouhot.lovable.app/#contact",
      offerings: {
        productManagement: "/product-owner",
        opsAutomation: "/ops-builder"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bmkzttcfxehvyodusqtr";
var mcp_default = defineMcp({
  name: "simon-babouhot-mcp",
  title: "Simon Babouhot \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools to explore Simon Babouhot's portfolio: profile, professional experience, and contact channels.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_experience_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
